## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "IBM Cloud Paks"
theme = "hugo-story"
baseURL = 'https://ibm.github.io/cloudpak-platform-paper/'


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-GLSBYZF7PG"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/caressofsteel/"
  twitter = "https://twitter.com/caressofsteel_"
  email = "caressofsteel@protonmail.com"
  instagram = "https://instagram.com"
  linkedin = "https://linkedin.com"
  telegram = "https://telegram.org"
